src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Groups;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: RestaurantRepository::class)]
class Restaurant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['restaurant:read'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['restaurant:read'])]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['restaurant:read'])]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    #[Groups(['restaurant:read'])]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['restaurant:read'])]
    private ?string $complement = null;

    #[ORM\Column(length: 255)]
    #[Groups(['restaurant:read'])]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255)]
    private ?string $siret = null;

    #[ORM\Column]
    #[Groups(['restaurant:read'])]
    private ?float $longitude = null;

    #[ORM\Column]
    #[Groups(['restaurant:read'])]
    private ?float $latitude = null;

    #[ORM\Column(length: 255)]
    #[Groups(['restaurant:read'])]
    private ?string $mail = null;

    #[ORM\Column(length: 255)]
    #[Groups(['restaurant:read'])]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $rib = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Groups(['restaurant:read'])]
    private ?string $logo = '';

    #[Vich\UploadableField(mapping: 'restaurant_image', fileNameProperty: 'logo')]
    private ?File $logoFile = null;

    #[ORM\Column]
    #[Groups(['restaurant:read'])]
    private ?int $nb_table = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['restaurant:read'])]
    private ?bool $a_decouvrir = null;

    #[ORM\OneToMany(mappedBy: 'restaurant', targetEntity: Reservation::class, orphanRemoval: true)]
    private Collection $reservations;

    #[ORM\OneToMany(mappedBy: 'restaurant', targetEntity: Avis::class)]
    private Collection $avis;

    #[ORM\OneToMany(mappedBy: 'restaurant', targetEntity: Plat::class, cascade: ["persist"], orphanRemoval: true)]
    private Collection $plats;

    #[ORM\OneToMany(mappedBy: 'restaurant', targetEntity: Table::class, orphanRemoval: true)]
    private Collection $tables;

    #[ORM\OneToMany(mappedBy: 'restaurant', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\ManyToMany(targetEntity: Utilisateur::class, inversedBy: 'adminRestaurants')]
    private Collection $administrateur;

    #[ORM\Column(nullable: true)]
    #[Groups(['restaurant:read'])]
    private ?bool $clickCollect = null;

    #[ORM\Column(length: 255)]
    #[Groups(['restaurant:read'])]
    private ?string $type = null;

    #[ORM\Column]
    #[Groups(['restaurant:read'])]
    private ?float $prix = null;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->plats = new ArrayCollection();
        $this->tables = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->administrateur = new ArrayCollection();
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getComplement(): ?string
    {
        return $this->complement;
    }

    public function setComplement(?string $complement): static
    {
        $this->complement = $complement;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): static
    {
        $this->siret = $siret;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): static
    {
        $this->mail = $mail;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getRib(): ?string
    {
        return $this->rib;
    }

    public function setRib(string $rib): static
    {
        $this->rib = $rib;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getNbTable(): ?int
    {
        return $this->nb_table;
    }

    public function setNbTable(int $nb_table): static
    {
        $this->nb_table = $nb_table;

        return $this;
    }

    public function isADecouvrir(): ?bool
    {
        return $this->a_decouvrir;
    }

    public function setADecouvrir(?bool $a_decouvrir): static
    {
        $this->a_decouvrir = $a_decouvrir;

        return $this;
    }

    public function isClickCollect(): ?bool
    {
        return $this->clickCollect;
    }

    public function setClickCollect(bool $clickCollect): static
    {
        $this->clickCollect = $clickCollect;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setRestaurant($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getRestaurant() === $this) {
                $reservation->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setRestaurant($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getRestaurant() === $this) {
                $avi->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Plat>
     */
    public function getPlats(): Collection
    {
        return $this->plats;
    }

    public function addPlat(Plat $plat): static
    {
        if (!$this->plats->contains($plat)) {
            $this->plats->add($plat);
            $plat->setRestaurant($this);
        }

        return $this;
    }

    public function removePlat(Plat $plat): static
    {
        if ($this->plats->removeElement($plat)) {
            // set the owning side to null (unless already changed)
            if ($plat->getRestaurant() === $this) {
                $plat->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Table>
     */
    public function getTables(): Collection
    {
        return $this->tables;
    }

    public function addTable(Table $table): static
    {
        if (!$this->tables->contains($table)) {
            $this->tables->add($table);
            $table->setRestaurant($this);
        }

        return $this;
    }

    public function removeTable(Table $table): static
    {
        if ($this->tables->removeElement($table)) {
            // set the owning side to null (unless already changed)
            if ($table->getRestaurant() === $this) {
                $table->setRestaurant(null);
            }
        }

        return $this;
    }

src/Form/RestaurantType.php
<?php

namespace App\Form;

use App\Entity\Restaurant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestaurantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class)
            ->add('description', TextType::class, ['required' => false])
            ->add('adresse', TextType::class)
            ->add('complement', TextType::class, ['required' => false])
            ->add('code_postal', TextType::class)
            ->add('siret', TextType::class)
            ->add('longitude', NumberType::class)
            ->add('latitude', NumberType::class)
            ->add('mail', TextType::class)
            ->add('telephone', TextType::class)
            ->add('rib', TextType::class)
            ->add('logo', TextType::class)
            ->add('nb_table', IntegerType::class)
            ->add('a_decouvrir', CheckboxType::class, ['required' => false])
            ->add('clickCollect', CheckboxType::class, ['required' => false])
            ->add('type', TextType::class)
            ->add('prix', NumberType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Restaurant::class,
        ]);
    }
}

src/Controller/Api/RestaurantController.php
<?php

namespace App\Controller\Api;

use App\Entity\Restaurant;
use App\Form\RestaurantType;
use App\Repository\RestaurantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\SerializerInterface;

#[Route('api/restaurants')]
class RestaurantController extends AbstractController
{
    public function __construct(
        private readonly RestaurantRepository $restaurantRepository
    ) {
    }


    #[Route('/', name: 'api_restaurant_index', methods: ['GET'])]
    public function index(SerializerInterface $serializer): Response
    {
        $restaurants = $this->restaurantRepository->findAll();
        return new Response(
            $serializer->serialize($restaurants, 'json', ['groups' => 'restaurant:read']),
            200,
            ['Content-Type' => 'application/json']
        );
    }

}

src/Controller/RestaurantController.php
<?php

namespace App\Controller;

use App\Entity\Restaurant;
use App\Form\RestaurantFormType;
use App\Form\RestaurantType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class RestaurantController extends \Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    #[Route('/restaurant/new', name: 'app_new_restaurant')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $restaurant = new Restaurant();
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($restaurant);
            $entityManager->flush();

            return $this->redirectToRoute('app_new_restaurant');
        }

        return $this->render('restaurant/new.html.twig', [
            'restaurantForm' => $form->createView(),
        ]);
    }

    #[Route('/restaurant/{id}/edit', name: 'app_edit_restaurant')]
    public function edit(Request $request, EntityManagerInterface $entityManager, Restaurant $restaurant): Response
    {
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Le formulaire a été soumis et est valide, mettez à jour le restaurant
            $entityManager->flush();

            // Redirigez l'utilisateur vers une page appropriée
            return $this->redirectToRoute('app_edit_restaurant', ['id' => $restaurant->getId()]);
        }

        return $this->render('restaurant/edit.html.twig', [
            'restaurantForm' => $form->createView(),
            'restaurant' => $restaurant,
        ]);
    }
}

templates/restaurant/_delete_form.html.twig
<form method="post" action="{{ path('app_restaurant_delete', {'id': restaurant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/restaurant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/restaurant/edit.html.twig
{% block title %}Modifier le restaurant {{ restaurant.nom }}{% endblock %}

{% block body %}
    <h1>Modifier le restaurant {{ restaurant.nom }}</h1>

    {{ form_start(restaurantForm) }}
    {{ form_row(restaurantForm.nom) }}
    {{ form_row(restaurantForm.description) }}
    {{ form_row(restaurantForm.adresse) }}
    {{ form_row(restaurantForm.complement) }}
    {{ form_row(restaurantForm.code_postal) }}
    {{ form_row(restaurantForm.siret) }}
    {{ form_row(restaurantForm.longitude) }}
    {{ form_row(restaurantForm.latitude) }}
    {{ form_row(restaurantForm.mail) }}
    {{ form_row(restaurantForm.telephone) }}
    {{ form_row(restaurantForm.rib) }}
    {{ form_row(restaurantForm.logo) }}
    {{ form_row(restaurantForm.nb_table) }}
    {{ form_row(restaurantForm.a_decouvrir) }}
    {{ form_row(restaurantForm.clickCollect) }}
    {{ form_row(restaurantForm.type) }}
    {{ form_row(restaurantForm.prix) }}

    <button type="submit" class="btn">Enregistrer les modifications</button>
    {{ form_end(restaurantForm) }}
{% endblock %}

templates/restaurant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant index{% endblock %}

{% block body %}
    <h1>Restaurant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Adresse</th>
                <th>Complement</th>
                <th>Code_postal</th>
                <th>Siret</th>
                <th>Longitude</th>
                <th>Latitude</th>
                <th>Mail</th>
                <th>Telephone</th>
                <th>Rib</th>
                <th>Logo</th>
                <th>Nb_table</th>
                <th>A_decouvrir</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for restaurant in restaurants %}
            <tr>
                <td>{{ restaurant.id }}</td>
                <td>{{ restaurant.nom }}</td>
                <td>{{ restaurant.description }}</td>
                <td>{{ restaurant.adresse }}</td>
                <td>{{ restaurant.complement }}</td>
                <td>{{ restaurant.codePostal }}</td>
                <td>{{ restaurant.siret }}</td>
                <td>{{ restaurant.longitude }}</td>
                <td>{{ restaurant.latitude }}</td>
                <td>{{ restaurant.mail }}</td>
                <td>{{ restaurant.telephone }}</td>
                <td>{{ restaurant.rib }}</td>
                <td>{{ restaurant.logo }}</td>
                <td>{{ restaurant.nbTable }}</td>
                <td>{{ restaurant.aDecouvrir ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_restaurant_show', {'id': restaurant.id}) }}">show</a>
                    <a href="{{ path('app_restaurant_edit', {'id': restaurant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="16">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_restaurant_new') }}">Create new</a>
{% endblock %}

templates/restaurant/new.html.twig
{% block title %}Ajouter un restaurant{% endblock %}

{% block body %}
    <h1>Ajouter un restaurant</h1>

    {{ form_start(restaurantForm) }}
    {{ form_row(restaurantForm.nom) }}
    {{ form_row(restaurantForm.description) }}
    {{ form_row(restaurantForm.adresse) }}
    {{ form_row(restaurantForm.complement) }}
    {{ form_row(restaurantForm.code_postal) }}
    {{ form_row(restaurantForm.siret) }}
    {{ form_row(restaurantForm.longitude) }}
    {{ form_row(restaurantForm.latitude) }}
    {{ form_row(restaurantForm.mail) }}
    {{ form_row(restaurantForm.telephone) }}
    {{ form_row(restaurantForm.rib) }}
    {{ form_row(restaurantForm.logo) }}
    {{ form_row(restaurantForm.nb_table) }}
    {{ form_row(restaurantForm.a_decouvrir) }}
    {{ form_row(restaurantForm.clickCollect) }}
    {{ form_row(restaurantForm.type) }}
    {{ form_row(restaurantForm.prix) }}

    <button type="submit" class="btn">Ajouter</button>
    {{ form_end(restaurantForm) }}
{% endblock %}

templates/restaurant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant{% endblock %}

{% block body %}
    <h1>Restaurant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ restaurant.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ restaurant.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ restaurant.description }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ restaurant.adresse }}</td>
            </tr>
            <tr>
                <th>Complement</th>
                <td>{{ restaurant.complement }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ restaurant.codePostal }}</td>
            </tr>
            <tr>
                <th>Siret</th>
                <td>{{ restaurant.siret }}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{ restaurant.longitude }}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{ restaurant.latitude }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ restaurant.mail }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ restaurant.telephone }}</td>
            </tr>
            <tr>
                <th>Rib</th>
                <td>{{ restaurant.rib }}</td>
            </tr>
            <tr>
                <th>Logo</th>
                <td>{{ restaurant.logo }}</td>
            </tr>
            <tr>
                <th>Nb_table</th>
                <td>{{ restaurant.nbTable }}</td>
            </tr>
            <tr>
                <th>A_decouvrir</th>
                <td>{{ restaurant.aDecouvrir ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_restaurant_index') }}">back to list</a>

    <a href="{{ path('app_restaurant_edit', {'id': restaurant.id}) }}">edit</a>

    {{ include('restaurant/_delete_form.html.twig') }}
{% endblock %}